name: CON FORZA
favicon: null
layout_spectrum: 0.40739895263686776
typography_spectrum: 0.5665729660540819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1679365204181522
  lightness: 0.8070934908464551
  saturation: 0.7550208664033562
  rhythmicContrast: 0.23519032448530197
purpose: []
